ALTER TABLE servers ENABLE ROW LEVEL SECURITY;
ALTER TABLE server_hosts ENABLE ROW LEVEL SECURITY;
ALTER TABLE server_statuses ENABLE ROW LEVEL SECURITY;
ALTER TABLE server_identities ENABLE ROW LEVEL SECURITY;

ALTER TABLE bots ENABLE ROW LEVEL SECURITY;
ALTER TABLE bot_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE bot_statuses ENABLE ROW LEVEL SECURITY;
ALTER TABLE bot_reply_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE bot_commands ENABLE ROW LEVEL SECURITY;

ALTER TABLE relays ENABLE ROW LEVEL SECURITY;
ALTER TABLE relay_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE relay_statuses ENABLE ROW LEVEL SECURITY;
